apiVersion: v1
appVersion: 1.0.0
name: base-infra
version: 1.0.0
description: A comprehensive base infrastructure chart for AWS including VPC, ECS, and essential resources
type: application
home: https://github.com/yourusername/terraform-templator
keywords:
  - aws
  - infrastructure
  - vpc
  - ecs
  - terraform
  - base
maintainers:
  - name: Your Name
    email: your.email@example.com
    url: https://github.com/yourusername
