locals:
  name: my-project
  environment: dev
  region: us-west-2

provider:
  aws:
    region: "us-west-2"
    profile: default

vpc:
  prime:
    module: 
    cidr: 10.0.0.0/16
    enable_nat_gateway: true
    enable_vpn: false
    subnets:
      - cidr: 10.0.1.0/24
        type: public
        availability_zone: us-west-2a
      - cidr: 10.0.2.0/24
        type: private
        availability_zone: us-west-2b
      - cidr: 10.0.3.0/24
        type: private
        availability_zone: us-west-2c

rds:
  prime:  
    engine: postgres
    engine_version: "14"
    instance_class: db.t3.micro
    allocated_storage: 20
    db_name: appdb
    username: admin # Should be provided via environment or secrets
